/**
 * Autopilot: clear stale tool output from agent requests in flight, without
 * ever costing more than it saves.
 *
 * Why this and not the proxy's general strategies: replayed over 33 real
 * Claude Code sessions with prompt-cache pricing, the general trim saved 6.7%
 * overall but made one session 13% MORE expensive, because every change to
 * history the cache already holds re-bills everything after it at the write
 * rate. Most of the bill sits in long sessions (94% of input cost came from
 * requests above 200k tokens), so the win is real, but only if each change
 * pays for its cache rewrite.
 *
 * The rules, modelled on the microcompact logic Claude Code ships (and keeps
 * switched off by a server flag), tightened for "never worse":
 *
 *  1. Only output of read-only, re-runnable tools is eligible (file reads,
 *     shell, search, web fetch). Answers the user gave, subagent reports and
 *     MCP results are never touched.
 *  2. The most recent `keepRecent` tool results always stay.
 *  3. Clearing happens in batches of at least `minClearTokens`, so each cache
 *     rewrite buys a lot.
 *  4. A cleared result stays cleared on every later request (ids are
 *     remembered, across restarts), so the prefix is byte-stable between
 *     batches and the cache keeps hitting.
 *  5. By default a batch is taken ONLY when the cache is cold anyway (idle
 *     longer than the request's own cache TTL), because the whole prompt is
 *     re-written on that request regardless, so clearing costs nothing and
 *     every later request is smaller. That makes it never-worse by
 *     construction, and measured: replaying every Claude Code session on the
 *     author's machine through this class, with real timestamps and cache
 *     pricing, it saved 9.8% of cache-weighted input cost (9.2% of raw input
 *     tokens, up to 37.6% in one long session) and made no session worse.
 *     Clearing on a warm cache when the saving "should" repay the rewrite
 *     (`paybackSafety` > 0) added 0.1% and made one session 0.13% worse: the
 *     future is not knowable, so it is off unless asked for.
 *
 * The model sees a one-line note in place of the output and can simply re-run
 * the tool; the file, command or URL is still in the tool call.
 */

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { estimateTokens } from "./tokens.js";

/** Tools whose output can be regenerated by calling them again. */
export const CLEARABLE_TOOLS = new Set([
  "Read", "Bash", "BashOutput", "Grep", "Glob", "LS", "WebFetch", "WebSearch", "NotebookRead",
  // Codex / OpenAI-style names for the same operations.
  "shell", "exec_command", "read_file", "list_dir", "grep_search", "file_search", "web_search",
]);

/** Tokens billed for one image inside a tool result (a full-size screenshot is ~1.6k on Claude). */
const IMAGE_TOKENS = 1600;

export interface AutoClearOptions {
  /** Most recent tool results that always stay. Default 3. */
  keepRecent?: number;
  /** Smallest batch worth a cache rewrite. Default 20,000 tokens. */
  minClearTokens?: number;
  /**
   * Warm-cache rule: clear only if the saving over the requests still to come
   * repays the rewrite this many times over. Requests still to come are
   * estimated as the number already made in this conversation. Default 0:
   * warm clearing off, cold cache only (the never-worse setting).
   */
  paybackSafety?: number;
  /** Where cleared ids persist so a restart does not un-clear (and re-bill) them. */
  statePath?: string;
}

export interface AutoClearResult {
  changed: boolean;
  /** Results cleared by this request's new batch (0 when none was taken). */
  newlyCleared: number;
  /** Tokens removed from this request, old batches included. */
  tokensRemoved: number;
  cold: boolean;
  reason: string;
  /** Index of the first message rewritten on this request (the cache breaks from here), or -1. */
  firstChanged: number;
}

interface Found {
  msg: number;
  block: number;
  id: string;
  tokens: number;
}

interface ConvState {
  last: number;
  requests: number;
}

export function clearedNote(tokens: number): string {
  return `[context-doctor: old tool output cleared to keep context lean (~${tokens} tokens). Run the tool again if you need it.]`;
}

function resultTokens(content: unknown, model?: string): number {
  if (typeof content === "string") return estimateTokens(content, model);
  if (!Array.isArray(content)) return estimateTokens(JSON.stringify(content ?? ""), model);
  let n = 0;
  for (const part of content as Array<Record<string, unknown>>) {
    if (part?.type === "image") n += IMAGE_TOKENS;
    else if (typeof part?.text === "string") n += estimateTokens(part.text, model);
    else n += estimateTokens(JSON.stringify(part ?? ""), model);
  }
  return n;
}

/** The cache TTL the request itself asked for: "1h" if any breakpoint says so, else 5 minutes. */
export function requestTtlMs(body: Record<string, unknown>): number {
  const json = JSON.stringify(body.system ?? "") + JSON.stringify(body.tools ?? "") + JSON.stringify((body.messages as unknown[] | undefined)?.slice(-3) ?? "");
  return /"ttl"\s*:\s*"1h"/.test(json) ? 3_600_000 : 300_000;
}

/**
 * A conversation's identity: its first user message plus its first tool call
 * id. The message alone can repeat across sessions (the same project context
 * opens every session in a folder); tool call ids are unique per session.
 * The model is left out on purpose: switching models mid-session keeps the
 * conversation (and the cleared set) but not the cache, which the TTL check
 * cannot see, so a model switch is treated as warm, the safe direction.
 */
function conversationKey(body: Record<string, unknown>): string {
  const messages = (body.messages as Array<Record<string, unknown>>) ?? [];
  const first = messages.find((m) => m?.role === "user");
  let firstToolId = "";
  for (const m of messages) {
    if (m?.role !== "assistant" || !Array.isArray(m.content)) continue;
    const t = (m.content as Array<Record<string, unknown>>).find((b) => b?.type === "tool_use");
    if (t) { firstToolId = String(t.id ?? ""); break; }
  }
  return createHash("sha1").update(JSON.stringify(first?.content ?? "").slice(0, 4000)).update(firstToolId).digest("hex");
}

export class AutoClearer {
  private cleared = new Map<string, number>();
  /** Tool results never change once sent, so their size is computed once per id. */
  private sizes = new Map<string, number>();
  private convs = new Map<string, ConvState>();
  private opts: Required<Omit<AutoClearOptions, "statePath">> & { statePath?: string };
  private dirty = false;

  constructor(options: AutoClearOptions = {}) {
    this.opts = {
      keepRecent: options.keepRecent ?? 3,
      minClearTokens: options.minClearTokens ?? 20_000,
      paybackSafety: options.paybackSafety ?? 0,
      statePath: options.statePath,
    };
    this.load();
  }

  /** Rewrite `body` (an Anthropic Messages request) in place. Never throws. */
  apply(body: Record<string, unknown>, now = Date.now()): AutoClearResult {
    const none = (reason: string, cold = false): AutoClearResult => ({ changed: false, newlyCleared: 0, tokensRemoved: 0, cold, reason, firstChanged: -1 });
    try {
      const messages = body.messages as Array<Record<string, unknown>> | undefined;
      if (!Array.isArray(messages) || messages.length === 0) return none("no messages");
      const model = typeof body.model === "string" ? body.model : undefined;

      const key = conversationKey(body);
      const conv = this.convs.get(key);
      const cold = !conv || now - conv.last > requestTtlMs(body);
      this.convs.set(key, { last: now, requests: (conv?.requests ?? 0) + 1 });
      if (this.convs.size > 2000) this.convs.delete(this.convs.keys().next().value!);

      // Tool names by id, from the assistant side.
      const toolName = new Map<string, string>();
      for (const m of messages) {
        if (m?.role !== "assistant" || !Array.isArray(m.content)) continue;
        for (const b of m.content as Array<Record<string, unknown>>) {
          if (b?.type === "tool_use" && typeof b.id === "string") toolName.set(b.id, String(b.name ?? ""));
        }
      }
      const results: Found[] = [];
      messages.forEach((m, i) => {
        if (m?.role !== "user" || !Array.isArray(m.content)) return;
        (m.content as Array<Record<string, unknown>>).forEach((b, j) => {
          if (b?.type !== "tool_result" || typeof b.tool_use_id !== "string") return;
          let tokens = this.sizes.get(b.tool_use_id);
          if (tokens === undefined) {
            tokens = resultTokens(b.content, model);
            this.sizes.set(b.tool_use_id, tokens);
            if (this.sizes.size > 100_000) this.sizes.delete(this.sizes.keys().next().value!);
          }
          results.push({ msg: i, block: j, id: b.tool_use_id, tokens });
        });
      });

      const eligible = results.slice(0, Math.max(0, results.length - this.opts.keepRecent))
        .filter((r) => CLEARABLE_TOOLS.has(toolName.get(r.id) ?? ""));
      const pending = eligible.filter((r) => !this.cleared.has(r.id) && r.tokens > 200);
      const pendingTokens = pending.reduce((n, r) => n + r.tokens, 0);

      let reason = "nothing to clear";
      let taken: Found[] = [];
      if (pendingTokens >= this.opts.minClearTokens) {
        if (cold) {
          taken = pending;
          reason = "cache cold: cleared for free";
        } else if (this.opts.paybackSafety > 0 && this.shouldClearWarm(messages, pending, pendingTokens, model, (conv?.requests ?? 0) + 1)) {
          taken = pending;
          reason = "cache warm: saving repays the rewrite";
        } else {
          reason = "cache warm: waiting, rewrite would not pay back yet";
        }
      } else if (pendingTokens > 0) {
        reason = `waiting for a ${Math.round(this.opts.minClearTokens / 1000)}k batch`;
      }
      for (const r of taken) this.cleared.set(r.id, r.tokens);
      if (taken.length) this.dirty = true;

      // Apply every clearing ever decided for this conversation, so the
      // prefix is identical to what was sent last time.
      let removed = 0;
      let changed = false;
      let firstChanged = -1;
      for (const r of results) {
        if (!this.cleared.has(r.id)) continue;
        const block = (messages[r.msg].content as Array<Record<string, unknown>>)[r.block];
        const note = clearedNote(this.cleared.get(r.id)!);
        if (block.content === note) continue;
        removed += Math.max(0, r.tokens - estimateTokens(note, model));
        (messages[r.msg].content as Array<Record<string, unknown>>)[r.block] = { ...block, content: note };
        changed = true;
        if (firstChanged === -1 || r.msg < firstChanged) firstChanged = r.msg;
      }
      this.save();
      return { changed, newlyCleared: taken.length, tokensRemoved: removed, cold, reason, firstChanged };
    } catch {
      return none("error: request forwarded unchanged");
    }
  }

  /**
   * Warm cache: clearing rewrites everything after the first cleared result
   * at the write rate (1.25x instead of 0.1x: 1.15x extra, once), and saves
   * the cleared tokens at the read rate (0.1x) on every later request.
   * Later requests are estimated as the number made so far (a conversation's
   * age is the best predictor of how long it keeps going), and the saving must
   * cover the rewrite `paybackSafety` times over.
   */
  private shouldClearWarm(messages: Array<Record<string, unknown>>, pending: Found[], pendingTokens: number, model: string | undefined, requestsSoFar: number): boolean {
    const first = Math.min(...pending.map((r) => r.msg));
    let suffix = -pendingTokens;
    for (let i = first; i < messages.length; i++) suffix += estimateTokens(JSON.stringify(messages[i]), model);
    const rewriteCost = 1.15 * Math.max(0, suffix);
    const saving = 0.1 * pendingTokens * requestsSoFar;
    return saving >= this.opts.paybackSafety * rewriteCost;
  }

  private load(): void {
    if (!this.opts.statePath || !existsSync(this.opts.statePath)) return;
    try {
      const data = JSON.parse(readFileSync(this.opts.statePath, "utf8")) as { cleared?: Array<[string, number]> };
      for (const [id, tokens] of data.cleared ?? []) this.cleared.set(id, tokens);
    } catch {
      /* a corrupt state file only means results may be re-cleared once */
    }
  }

  private save(): void {
    if (!this.dirty || !this.opts.statePath) return;
    this.dirty = false;
    try {
      // Newest 50k ids: far more than any live session holds.
      const entries = [...this.cleared.entries()].slice(-50_000);
      mkdirSync(dirname(this.opts.statePath), { recursive: true });
      writeFileSync(this.opts.statePath, JSON.stringify({ cleared: entries }));
    } catch {
      /* persistence is best effort */
    }
  }
}
